# -*- coding: utf-8 -*-
"""tests/test_main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ax2e_0v7ao3FGat4mVQKWyIVdFkJS7pA
"""

from fastapi.testclient import TestClient
from main import app

client = TestClient(app)

def test_health_check():
    response = client.get("/")
    assert response.status_code == 200
    assert response.json() == {"status": "API is running"}

def test_add_requirement():
    requirement_data = {
        "id": 1,
        "title": "Dark mode support",
        "description": "Add dark mode to the application"
    }
    response = client.post("/requirements", json=requirement_data)
    assert response.status_code == 200
    assert "priority" in response.json()

def test_list_requirements():
    response = client.get("/requirements")
    assert response.status_code == 200
    assert isinstance(response.json(), list)

def test_add_feedback():
    feedback_data = {
        "requirement_id": 1,
        "feedback_text": "This feature is essential for accessibility."
    }
    response = client.post("/feedback", json=feedback_data)
    assert response.status_code == 200
    assert response.json()["feedback_text"] == feedback_data["feedback_text"]